version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/USER_APP
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: USER_APP
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
